### ISSUE TITLE
Add completion support for dependencies

### ISSUE THREAD

**Issue by aberman** [ostinelli/SublimErl#15]
Right now, the dependencies in the directory specified by the lib_dirs are not factored into the code completion.  It would be great to add support for dependencies.

**Comment by ostinelli** [comment]
they should be, see #12

have you tried latest version?

r.

**Comment by aberman** [comment]
I have the latest version and it's definitely not working.  I have the lib_dirs set to deps in my rebar.config file and none of those dependencies are showing up in the autocomplete.

**Comment by ostinelli** [comment]
rebar.config's contents are ignored. every .beam file under the project root get parsed.

if you'd like me to fix the issue you are experiencing, please put together some code that i can download to reproduce this error, and state the exact steps needed to do so.

thank you,

r.

**Comment by ostinelli** [comment]
this project works perfectly with sublimerl:
https://github.com/esl/ejabberd

so for example if you open the file `ejabberd/apps/ejabberd/src/ejabberd.erl`, when you can type code in it you'll see that the autocomplete suggestions will include the module `cuesport.erl` which is located into `/ejabberd/deps/cuesport/src/` (a dependency).

can you tell me which differences there are in comparison to yours?

**Comment by aberman** [comment]
Here you go: https://github.com/aberman/sublimerl_test
1.  Run rebar get-deps
2.  Run rebar compile
3.  Start Sublime
4.  Open sublimerl_test.erl
5.  Try typing jiffy or jiffy: and nothing shows up for completion.

**Comment by ostinelli** [comment]
working on it, should probably have a solution within days.

**Comment by ostinelli** [comment]
Hi @aberman, can you check if 09788fa59e593ea5058619cf38f665e5e383adf9 fixes it?

thanks,

r.

**Comment by aberman** [comment]
Hey @ostinelli, it's still not working.

**Comment by ostinelli** [comment]
it is working here, using your code, following your instructions.

![Jiffy screenshot](http://www.ostinelli.net/_out_images/temp/jiffy.png)

unfortunately, unless we can identify what is not running for you, i don't have anything to try (since it's working).
- do you have the compiled .beam files in `deps/jiffy/ebin` and `deps/proper/ebin` (which come after the manual step you've defined here above `rebar get-deps`)?
- do you have the compiled project files in `ebin`? (if not, please try 59d98e6194c4cfb2af16b24fd0784d5544536666 which fixes an issue with rebar needing to know where git is)
- what is the content of the `Current-Project.disasm` and `Current-Project.completions` files in the plugin's directory? (try deleting them and reopening Sublime Text)

the completions are built when a file gets 'activated' in the project window. try clicking on another tab then back to the project's file (i.e. `sublimerl_test.erl`)

otherwise please explain in a very detailed way what you are doing (i.e. which file you open up and so) so that i can try to reproduce, or shoot a brief video ^^_

r.

**Comment by aberman** [comment]
I nuked my SublimErl installation and redownloaded it and made sure all Erlang processes were killed and it appears to be working now.  Awesome stuff, Roberto!

**Comment by ostinelli** [comment]
thank you @aberman :)

r.
